name: Manually triggered workflow

on:
  workflow_dispatch:
    inputs:
      access-key-id:
        description: 'Acess Key ID'
        required: true
        default: ''
      secret-access-key:
        description: 'Secret Access Key'
        required: true
        default: ''
  # push:
  #   branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node awsClient.js
        with:
          access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}