name: Node.js CI

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - id: install-aws-cli
      uses: unfor19/install-aws-cli-action@v1
      with:
        version: 2 # default
        verbose: false # default
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-2
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    - run: rm pageShot.png
    - run: npm run start
    - name: Upload to S3
      run: |
        aws s3 sync pageShot.png s3://bonango.io-screenshots