name: Manually triggered workflow

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: node awsClient.js
      inputs:
        accessKeyId:
          description: 'Acess Key ID'
          default: '${{secrets.AWS_ACCESS_KEY_ID}}'
        secretAccessKey:
          description: 'Secret Access Key'
          default: '${{secrets.AWS_SECRET_ACCESS_KEY}}'